[book]
authors = ["Buckminsterfullerene02"]
language = "en"
multilingual = false
src = "src"
title = "A Comprehensive Introduction to Unreal Engine Modding"

[output.html]
additional-css = ["css/custom.css"]